# This is the BetterPortals configuration file
# Many of these values should not be changed unless you know what you are doing

# WARNING: The portal effect size is the biggest performance sink, higher numbers can cause tons of lag!
# The number of blocks that the portal effect will render
# to the up, down, forwards and backwards of the portal
# (the total width of the effect is twice this)
portalEffectSizeXZ: 13

# Same as the previous, but up/down instead
portalEffectSizeY: 7

# The closest portal in this range will be activated
# All others are discarded
portalActivationDistance: 20

portalBlockUpdateInterval: 20 # How often the portal will re-check for the blocks around it
blockStateRefreshInterval: 40 # How often modified block states are resent to the player

# Delay between portal autosaves, in ticks. Set to -1 to disable
portalSaveInterval: 6000

enableEntitySupport: true

# If this is true, the below is always treated like it is 1
checkForEntitiesEveryTick: false
entityCheckInterval: 7 # How often the portal will check for surrounding entities

# Interval for sending entity metadata updates in ticks (higher will improve performance, this is an expensive process, both for network bandwidth and CPU)
entityMetadataUpdateInterval: 6

# Setting this to true will allow you to see straight through a portal
# NOTE: This generally makes it look a bit less convincing, since it's easier to see when the player's client doesn't quite keep up
hidePortalBlocks: true

# How close portals can spawn to each other, in blocks
minimumPortalSpawnDistance: 6

# Change this to FINE, FINER or FINEST to enable debug logging
logLevel: INFO

# The update check nags you to update if you're not on latest
enableUpdateCheck: true

# Enables the /bp test ... commands. These shouldn't be used in normal plugin use.
enableTestingCommands: false

# The maximum size of portals in blocks. The x is width and y is height
# This should never be larger than twice the portal effect size
# Larger portals tend to look less good, so the default values work well
maxPortalSize:
  x: 5
  y: 5

# Stores the offset from the corners of the portal where the collision box will be
# This collision box is how the portal effect is calculated
# (if the ray from the player's view to the block being tested intersects this box it will be considered visible through the portal)
# The default values are tuned to work fairly well, so I don't recommend changing these
portalCollisionBox:
  x: 0.50
  y: 0.50
  z: 0.50

# Worlds where the plugin will fall back to the vanilla portal logic
disabledWorlds:
  - 'some_world'

# How long the plugin waits before rendering portals after switching worlds.
# Useful to deal with lag that some players get just after switching worlds.
# Set to 0 to disable
waitTimeAfterSwitchingWorlds: 1

# Portal view background blocks for specific worlds
# If no background block is found for a world, the default for the world type will be used
# Overworld: white concrete
# Nether: Red concrete
# End: Black concrete
worldBackgroundBlocks:
  'example': STONE

# Overrides all worldBackgroundBlocks if not empty
backgroundBlock: ''


teleportCooldown: 2 # How long to wait before a player can go back after going through a portal (0 to disable)

# Enables or disables the default world connections between the default overworld and nether worlds if they exist
enableDefaultWorldConnections: true

# The interval to place light blocks replacing air blocks. These are used to avoid the destination of the portal being too dark
# Set to -1 to disable (or 0)
# This option does nothing on versions below 1.18
# 7 is a reasonable value to use if you want to try this out
lightBlockInterval: -1

# The light level to use on the light blocks specified above instead of the default value
# By default this will be set based on the dimension (nether dimmer than overworld), on time of day (dark at night), and on Y level.
# If in the overworld, the level will be set to darker if in a cave
forceLightLevel: -1

# Stores the links between worlds. By default, two links will be added, as said above
# There are two links for the overworld and the nether - one for each way.
# This is to allow one way links between dimensions
# The x and z coordinates of the portals are multiplied by the coordinateRescalingFactor to spawn portals
# The min and max spawn y limit where portals can spawn - for instance you should not be able to spawn portals above the nether ceiling
worldConnections: {}
  #'0':
  #  originWorld: 'example'
  #  destinationWorld: 'example_nether'
  #  minSpawnY: 5 # Leave blank for automatically set to world size
  #  maxSpawnY: 122 # Leave blank for automatically set to world size
  #  coordinateRescalingFactor: 0.125
  #'1':
  #  originWorld: 'example_nether'
  #  destinationWorld: 'example'
  #  minSpawnY: 5 # Leave blank for automatically set to world size
  #  maxSpawnY: 250 # Leave blank for automatically set to world size
  #  coordinateRescalingFactor: 8.0

# While a portal is finding a destination position, it checks the chunks over multiple ticks to avoid completely freezing the server
# This specifies the amount of time allowed per-tick (in milliseconds)
allowedSpawnTimePerTick: 35

# Allows for setting a proxy server to allow cross-server portals
proxy:
  enableProxy: false
  proxyAddress: ""
  proxyPort: 25510
  key: "" # A UUID used for encrypted communication with the proxy. You should set this to the UUID in the BetterPortals config on the bungee side.
  reconnectionDelay: 300 # Delay in ticks before attempting a reconnection to the proxy if disconnected (default 30 seconds) Set to -1 to disable.

  # Change this to the name of this server in the bungeecord config.yml
  serverName: ""

  # Whether to display a warning if a player's selection is missing upon switching between two servers which both have BetterPortals.
  # This shouldn't happen, unless UUID forwarding is disabled, in which case it makes sense to disable this warning message.
  # UUID forwarding is required for selection syncing between servers.
  warnOnMissingSelection: true

  keepAlive: true # Whether or not to enable keepAlive on the socket

# Will randomly swap some blocks between the two ends of a nether portal when it's made, makes a cool effect.
dimensionBlend:
  enable: false
  fallOffRate: 0.15 # Low values mean a greater distance

chatMessages:
  prefix: "&7[&aBetterPortals&7]&a "
  messageColor: "&a" # One colour that chat messages without a full prefix use

  notEnoughPerms: "You do not have permission to use this command!"
  mustBePlayer: "You must be a player to use this command"
  mustMakeSelection: "You must make a selection first"
  invalidSelection: "Invalid selection! Portal selections must be on the two corners of a portal"
  mustSelectBothSides: "You must select both sides of a portal first. For info, run /bp help"
  mustSelectOrigin: "You must select the origin of the portal on this server"
  wrongNumberOfArgs: "Wrong number of arguments. Run /bp help for help."
  noCommands: "You don't have permission to use any sub-commands"
  invalidArgs: "One of your arguments was invalid. Run /bp help for help."
  differentSizes: "The origin and destination portal must be of the same size"
  noPortalCloseEnough: "No portal close enough found"
  removeNotOwnedByPlayer: "You do not have permission to remove portals created by other people"
  nameNotOwnedbyPlayer: "You don't have permission to set the name of portals created by other people"
  unknownCommand: "Unknown Command. For help, run /bp help"
  proxyDisabled: "Unable to reconnect to the proxy: it is not enabled!"
  alreadyConnected: "Unable to reconnect to the proxy: the server is already connected!"
  horizontalIssues: "Warning: horizontal portals with different origin/destination directions can cause issues with block rotations - not all blocks can be rotated in every direction"
  noName: "This portal has no name"
  nameNetherPortal: "You can't set the name of a nether portal"
  seeThroughPortalDisabled: "All nether portals will now look like vanilla portals to you!"
  seeThroughPortalEnabled: "All eligible nether portals will now show you what's on the other side."

  # Printed if a player lights a portal in an unlinked world
  # To disable, just remove all the text inside the quotes
  noWorldLink: "Unfortunately, this portal will not be lit since the world that you are in is not linked. (if you have changed the name of your world in server.properties, you need to change it in the config)
                If you believe this to be a mistake, contact an admin and link this wiki page for adding a world link: https://github.com/Lauriethefish/BetterPortals/wiki/Editing-the-Config-file#world-connections
                BetterPortals overrides the behaviour of plugins like MultiverseNetherPortals, so these should be uninstalled unless you're in a world that is manually excluded in the config.
                This message can be disabled in the BetterPortals config"

  # Printed if the player lights a portal over the size limit
  # To disable, just remove all the text inside the quotes.
  portalTooBig: "This portal is too big. The current size limit is {size}. You can increase it in the BetterPortals config.
                Please contact an admin if you want this changed."

  # Printed if the player walks through a vanilla nether portal
  # To disable, just remove all of the text inside the quotes
  vanillaPortal: "This is a vanilla nether portal. If you want to view through this portal, you will need to relight it."

  outOfDate: "Your version of BetterPortals is out of date. ({current} vs {new}). You can download the latest release from {url}"

  reload: "Reloaded plugin"
  originPortalSet: "Origin portal set"
  destPortalSet: "Destination portal set"
  portalsLinked: "Portals linked successfully"
  portalRemoved: "Portal removed"
  startedReconnection: "Started reconnecting to the proxy. See console for details."
  changedName: "Successfully changed the portal name"
  currentName: "The name for this portal is: {name}"
  allowsItems: "This portal allows item teleportation"
  doesNotAllowItems: "This portal does not allow item teleportation"
  changedAllowsItems: "Successfully set that the portal allows item teleportation"
  changedDoesNotAllowItems: "Successfully set that the portal does not allow item teleportation"
  help: "Sub Commands"

  setPosA: "Set position A"
  setPosB: "Set position B"

portalWandName: "&aPortal Wand"