name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 16.0.2
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew clean build
      - uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: build/libs/*all.jar
      - name: Get short sha
        if: ${{ github.ref == 'refs/heads/master' }}
        id: get_sha
        run: |
          echo "::set-output name=SHORT_SHA::$(git rev-parse HEAD | cut -c 1-8)"
      - name: Set Publish JAR
        if: ${{ github.ref == 'refs/heads/master' }}
        run: echo "PUBLISH_JAR=$(find build/libs/*all.jar -print -quit)" >> $GITHUB_ENV
      - name: Publish JAR to webhook
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: tsickert/discord-webhook@v3.2.0
        with:
          # Url is github secret, so it doesn't get leaked
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "`${{ steps.get_sha.outputs.SHORT_SHA }}` - `${{ github.event.head_commit.message }}`"
          username: "BetterPortals Dev Builds"
          avatar-url: "https://i.imgur.com/4l67APG.png"
          filename: ${{ env.PUBLISH_JAR }}
      - name: Stop gradle daemons
        run: gradle -stop